config/routes.rb
Rails.application.routes.draw do
  
 
  
  get '/trial' , to: 'welcome#index'

  get 'womanworker/home', to: 'womanworker#home'

get  'case/new', to: 'case#new'
post  'case/create', to: 'case#create'
  resources :cases
  
  get '/', to:'static#home'
  get  '/about', to: 'static#about'
  get '/contact', to: 'static#contact'
  get '/dependent', to: 'static#dependent'
  
  get 'welcome/update_cities', as: 'update_cities'
get 'welcome/show'
  
  
end

app/models/case.rb
class Case < ActiveRecord::Base
	
end

app/models/city.rb
class City < ActiveRecord::Base
  belongs_to :country
end

app/models/country.rb
class Country < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/case_controller.rb
class CaseController < ApplicationController
  def new
  	@case = Case.new(params[:case])
  end

  def create	
    @case = Case.new()
    if @case.save
      flash[:success] = "Your report has successfully been submited!"
      redirect_to '/'
    else
      render 'new'
    end
  
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
  
  def dependent
  	
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @countries = Country.all
    @cities = City.where("country_id = ?", Country.first.id)
  end
   
  def show
    @city = City.find_by("id = ?", params[:trip][:city_id])
  end
  
  def update_cities
    @cities = City.where("country_id = ?", params[:country_id])
    respond_to do |format|
      format.js
    end
  end
end

app/controllers/womanworker_controller.rb
class WomanworkerController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/case_helper.rb
module CaseHelper
end

app/helpers/layout_helper.rb
module LayoutHelper

  def bootstrap_version
    # Choose the Bootstrap version you would like to use from the CDN
    "3.0.3"
  end

end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/womanworker_helper.rb
module WomanworkerHelper
end

app/views/case/create.html.erb
<h1>Case#create</h1>
<p>Find me in app/views/case/create.html.erb</p>

app/views/case/new.html.erb
<% provide(:title, 'Report a case') %>
<%= render 'layouts/mainnav' %>



<%= form_for :case, url: '/case/create' do |f| %>
<div>
  <p>
    <%= f.label :continent %><br>
    <%= f.select :continent , ["Select a continent","Africa","North America","South America","Asia","Europe","Australia","Antarctica"] %>
  </p>
 
  <p>
    <%= f.label :country %><br>
    <%= f.text_field :country %>
  </p>

  <p>
    <%= f.label :district %><br>
    <%= f.text_field :district %>
  </p>
  <p>
    <%= f.label :case_category %><br>
    <%= f.select :case_category, ["Select a category of violence","Dating violence" , "Domestic and intimate partner violence" ,"Emotional abuse" , "Human trafficking", "Same-sex relationship violence" , "Sexual assault and abuse" , "Stalking" , "Violence against immigrant and refugee women" , "Violence against women at work" , "Violence against women with disabilities"]%>
  </p>
   <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>

</div>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/case/show.html.erb
<h1>Case#show</h1>
<p>Find me in app/views/case/show.html.erb</p>

app/views/cities/_city.html.erb
<!-- app/views/cities/_city.html.erb -->
  
<option value="<%= city.id %>"><%= city.name.titleize %></option>

app/views/layouts/_logo.html.erb
<div id="logo">
          <div id="logo_text">
              <!-- class="logo_colour", allows you to change the colour of the text -->
              <h1><a href="/">women<span class="logo_colour">ReportPlatform</span></a></h1>
              <h2>Bridging the gap between the women and their leaders.</h2>
          </div>
          <p style="float: right; padding-top: 65px;"><%= image_tag("twitter.png", :size => "", :alt => "Show Group") %> <%= image_tag("facebook.png", :size => "", :alt => "Show Group") %><%= image_tag("rss.png", :size => "", :alt => "Show Group") %>
          </p>
</div>

app/views/layouts/_mainnav.html.erb
    <header>
        <%= render 'layouts/logo'%>
      <nav>
        <ul class="sf-menu" id="nav">
          <li class="selected"><a href="/">Home</a></li>
          <li><a href="/about">My About</a></li>
          <li><a href="/contact">Contact Us</a></li>
          <li><a href="case/new">Report A Case</a></li>
        </ul>
      </nav>
    </header>

app/views/layouts/_woman_worker_nav.html.erb
    <header>
      <%= render 'layouts/logo' %>
      <nav>
        <ul class="sf-menu" id="nav">
            <li class="selected"><a href="womanworker/home">Home</a></li>
            <li><a href="case/new">Report A Case</a></li>
            <li><a href="">Submit Annual Report</a></li>
            <li><a href="#">Graphical Reports</a>
              <ul>
                <li><a href="#">Global Reports</a></li>
                <li><a href="#">Continent Based Reports </a>
                <li><a href="#">Country/State Based Reports</a></li>
                <li><a href="#">District/Province Based Reports</a></li>
              </ul>
            </li>

            <li><a href="#">Map Reports</a>
              <ul>
                <li><a href="#">Global Reports</a></li>
                <li><a href="#">Continent Based Reports </a>
                <li><a href="#">Country/State Based Reports</a></li>
                <li><a href="#">District/Province Based Reports</a></li>
              </ul>
            </li>
            
            <li><a href="/about">About</a></li>
            <li><a href="/contact">Contact</a></li>

        </ul>
      </nav>
    </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  
   <%= stylesheet_link_tag 'stylesheets/custom', :media => 'screen' %>


  <%= csrf_meta_tags %>

  

</head>
<body>
<div id="main">
    
    
    <%= yield %>
    <footer>
      <p>Copyright &copy; womenReportPlatform</p>
    </footer>
  </div>
  <p>&nbsp;</p>
  <!-- javascript at the bottom for fast page loading -->
  <script type="text/javascript" src="js/jquery.js"></script>
  <script type="text/javascript" src="js/jquery.easing-sooper.js"></script>
  <script type="text/javascript" src="js/jquery.sooperfish.js"></script>
  <script type="text/javascript" src="js/image_fade.js"></script>
  <script type="text/javascript">
    $(document).ready(function() {
      $('ul.sf-menu').sooperfish();
    });
  </script>


</body>
</html>

app/views/welcome/index.html.erb
<!-- app/views/welcome/index.html.erb -->
  
<%= form_for :trip, url: {action: "show"}, html: {method: "get"} do |f| %>
  <%= f.select :country_id, options_for_select(@countries.collect { |country|
    [country.name.titleize, country.id] }, 1), {}, { id: 'countries_select' } %>
  <%= f.select :city_id, options_for_select(@cities.collect { |city|
    [city.name.titleize, city.id] }, 0), {}, { id: 'cities_select' } %>
  <%= f.submit "Go!" %>
<% end %>

app/views/welcome/show.html.erb
<!-- app/views/welcome/show.html.erb -->
  
<p><%= @city.name.titleize %></p>
<p><%= link_to 'Go Back', welcome_index_path %></p>

app/views/womanworker/home.html.erb
<% provide(:title, 'Home') %>
 <%= render 'layouts/woman_worker_nav' %>
<div id="site_content">
	<div id="sidebar_container">
		<div class="gallery">
          <ul class="images">
            <li class="show"><%= image_tag("woman1.jpeg", :size => "450x450", :alt => "Show Group" ) %></li>
            <li><%= image_tag("woman2.jpeg", :size => "450x450", :alt => "Show Group" ) %></li>
          </ul>
        </div>
	 </div>
	<div id="content">
	        <h1>Welcome to the womenReportPlatform</h1>
	        <p>This is a platform for women to report any cases of violence to their leaders. You just have to fill a form with the details of the case you are reporting and your leaders will be able to know about it.To  do this you are required to create an account and login. There is no need to be afraid because your privacy is guarateed.Feel free to have your say.</p>
	        <h3>what you need to know</h3>
	        <p>Please give the current residential information because it is important for your leaders in  their planning decisions. </p>
	</div>
</div>